#!/bin/bash

# Deployment script for Render.com

echo "==========================================="
echo "Physical AI & Humanoid Robotics RAG Backend"
echo "Deployment Preparation Script"
echo "==========================================="

echo ""
echo "Before deploying to Render.com, please ensure you have:"
echo "1. A GitHub repository with this code"
echo "2. A Render account (https://render.com)"
echo ""

echo "Required Environment Variables for Render.com:"
echo ""
echo "API Keys & Services:"
echo "  - GEMINI_KEY: Your Google Gemini API key"
echo "  - QDRANT_URL: Your Qdrant Cloud URL"
echo "  - QDRANT_API_KEY: Your Qdrant API key"
echo ""
echo "Database:"
echo "  - NEON_DB_HOST: Your Neon database host"
echo "  - NEON_DB_USER: Your Neon database username"
echo "  - NEON_DB_PASSWORD: Your Neon database password"
echo "  - NEON_DATABASE_URL: Your full Neon database connection string"
echo ""
echo "Security:"
echo "  - BETTER_AUTH_SECRET: Generate a secure secret key (32+ random chars)"
echo "  - BETTER_AUTH_URL: Your frontend URL (e.g., https://your-frontend.onrender.com)"
echo ""
echo "OAuth (Optional):"
echo "  - GOOGLE_CLIENT_ID: Your Google OAuth client ID"
echo "  - GOOGLE_CLIENT_SECRET: Your Google OAuth client secret"
echo "  - GITHUB_CLIENT_ID: Your GitHub OAuth client ID"
echo "  - GITHUB_CLIENT_SECRET: Your GitHub OAuth client secret"
echo ""

echo "Deployment Steps:"
echo "1. Push this code to your GitHub repository"
echo "2. Go to https://dashboard.render.com"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect your GitHub repository"
echo "5. Render will use the render.yaml configuration"
echo "6. Add the environment variables in the Render dashboard"
echo "7. Deploy!"
echo ""

echo "After deployment:"
echo "- Visit https://your-service.onrender.com/health to check health"
echo "- Visit https://your-service.onrender.com/api/health for API health"
echo "- Test the RAG functionality at https://your-service.onrender.com/api/query"
echo ""

echo "==========================================="
echo "Deployment preparation complete!"
echo "==========================================="